name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.21"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"
          cache: true

      - name: Test
        run: |
          go test -v -coverprofile=profile.cov ./...

      - name: Send coverage
        if: always()
        uses: codecov/codecov-action@v3
        with:
          files: profile.cov
          flags: Go-${{ matrix.go }}
